export enum StatusOfFamilyTarget {
  REACHED = 'REACHED',

  NOT_REACHED_YET = 'NOT_REACHED_YET',

  FAMILY_MOVED = 'FAMILY_MOVED',

  FAMILY_NOT_EXIST = 'FAMILY_NOT_EXIST',

  FAMILY_REFUSED = 'FAMILY_REFUSED',

  NOT_COVERED_OTHER = 'NOT_COVERED_OTHER',
}
